### ISSUE TITLE
Is this plug in available for ROS (noetic) GAZEBO-11 ?

### ISSUE THREAD

**Issue by XiaoFeng-Kuang** [roboticsgroup/roboticsgroup_upatras_gazebo_plugins#4]
Dear Sir, 
I am trying to use this plug-in in an environment 
Ubuntu 20.04 
ROS (noetic) 
GAZEBO-11
MoveIt 1

I see the plug-in loaded into the gazebo world, but when I used rqt to control the joint, it does not work

![1](https://user-images.githubusercontent.com/71340432/219515757-07a1f88b-11bd-4413-b142-ff8a0ee6108b.png)

Thank you for your time.

**Comment by nlamprian** [comment]
It's hard to suggest something meaningful without inspecting your model.

Try removing maxEffort or adding `<hasPID />` to see if anything makes it move, and from there on, keep tweaking values (for the plugin, as well as the model). You can also play with the transmission of the joints (change it between position and effort).
